[package]
authors.workspace = true
categories.workspace = true
description = "A webauthn authenticator supporting passkeys."
edition.workspace = true
include = ["../LICENSE-APACHE", "../LICENSE-MIT", "src/"]
keywords.workspace = true
license.workspace = true
name = "passkey-authenticator"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.5.0"

[lints]
workspace = true

[features]
default = ["std"]
std = [
  "coset/std",
  "p256/std",
  "passkey-types/std",
  "rand/std",
  "rand/std_rng",
]
testable = ["dep:mockall", "passkey-types/testable"]
tokio = ["dep:tokio"]

[dependencies]
async-trait = "0.1"
coset = { workspace = true }
hashbrown = { version = "0.17", default-features = false, features = ["default-hasher"] }
log = "0.4"
mockall = { version = "0.11", optional = true }
p256 = { version = "0.13", default-features = false, features = ["alloc", "arithmetic", "ecdsa", "pkcs8"] }
passkey-types = { path = "../passkey-types", version = "0.5", default-features = false }
rand = { version = "0.8", default-features = false, features = ["alloc", "getrandom"] }
tokio = { version = "1", features = ["sync"], optional = true }

[dev-dependencies]
authenticator = { version = "0.4", default-features = false, features = [
  "crypto_dummy",
] }
ciborium = "0.2"
generic-array = { version = "=0.14.7", default-features = false }
mockall = { version = "0.11" }
passkey-types = { path = "../passkey-types", version = "0.5", features = [
  "testable",
] }
serde_cbor = "0.11"
signature = { version = "2", features = ["rand_core"] }
tokio = { version = "1", features = ["macros", "rt", "sync"] }
